### ISSUE TITLE
Consider widening domain of bf:seriesEnumeration from Instance to Resource (or add bflc:Relationship)

### ISSUE THREAD

**Issue by schlawiner** [lcnetdev/bibframe-ontology#100]
The recent Conversion Specification document "Process notes" (https://www.loc.gov/bibframe/mtbf/ConvSpec-Process0-8-v2.1.docx) specifies that series statements should be described using bflc:relationship/bflc:Relationship and in examples 6.2, 6.3, 6.4 and 6.5 attach bf:seriesEnumeration to a bflc:Relationship object. 

Yet, the domain of seriesEnumeration is currenty still bf:Instance: see http://id.loc.gov/ontologies/bibframe/seriesEnumeration.

**Comment by jodiw01** [comment]
updated in ontology update v2.4
