### ISSUE TITLE
Add class bf:Danacode as subclass of bf:Identifier

### ISSUE THREAD

**Issue by NancyL** [lcnetdev/bibframe-ontology#102]
Danacode is a unique numeric commercial book identifier used mainly in Israel. It is recognized and registered as Standard Identifier Source Code at https://id.loc.gov/vocabulary/identifiers/danacode.html. Our catalogers find these identifiers regularly in Israeli books and would like to add them as identifiers.

The general website for Danacode is at: www.danacode.com

**Comment by klngwll** [comment]
Just for reference, In Libris we also added `Danacode` as a subClass of `Identifier` in our KB Vocabulary at the request of catalogers. So +1 on usage.

https://id.kb.se/vocab/Danacode

**Comment by kirkhess** [comment]
If we're adding identifiers, I think it is time to add OCN as a subclass of bf:Identifier, aka: https://id.kb.se/vocab/WorldCatNumber. 

See https://github.com/lcnetdev/bibframe2marc/issues/13 - this would assist in fixing this problem.

**Comment by jodiw01** [comment]
This was addressed in https://github.com/lcnetdev/bibframe-ontology/issues/44

"All members of the [Identifier Sources scheme](https://id.loc.gov/vocabulary/identifiers) are now of type bf:Identifier to make clear their usability in Bibframe."
