### ISSUE TITLE
Changelog and git version tagging

### ISSUE THREAD

**Issue by klngwll** [lcnetdev/bibframe-ontology#103]
Just a friendly reminder that the [Changelog.md](https://github.com/lcnetdev/bibframe-ontology/blob/main/CHANGELOG.md) is missing the Bibframe 2.2 changes 🙂
(At the National Library of Sweden we found the changelog to be very useful in our work aligning updates in Libris XL.)

Another related question is if you have thought about tagging the releases in git? (as described in https://git-scm.com/book/en/v2/Git-Basics-Tagging)

**Comment by kefo** [comment]
Huh.  I plum forgot about the Changelog; we were in such a rush.  I'll see what I can do.

If it would be beneficial to tag releases, happy to do that moving forward.  Thanks for the suggestion.

**Comment by klngwll** [comment]
Thanks Kevin!

Just for reference, we do tagging (but not complete "github releases") -> https://github.com/libris/definitions/tags

**Comment by kefo** [comment]
Long time coming, but looks like we got this sorted out.  And some tagging.
