### ISSUE TITLE
dcterms:modified note inconsistent with actual spec

### ISSUE THREAD

**Issue by olufine** [lcnetdev/bibframe-ontology#105]
Hi, 
The file bibframe.rdf published here and on the loc.gov website has several owl:ObjectProperty declarations containing a comment to the effect that the range specification is removed, although the rdfs:range assertion is still present. 
Example:
` <owl:ObjectProperty rdf:about="http://id.loc.gov/ontologies/bibframe/place">
  <rdfs:domain rdf:resource="http://www.w3.org/2000/01/rdf-schema#Resource"/>
  **<rdfs:range rdf:resource="http://www.w3.org/2000/01/rdf-schema#Resource"/>**
  <skos:definition>Geographic location or place entity associated with a resource or element of description, such as the place associated with the publication, printing, distribution, issue, release or production of a resource, place of an event.
  </skos:definition>
  <rdfs:label>Place</rdfs:label>
  <dcterms:modified>2016-04-21 (New)</dcterms:modified>
 <dcterms:modified>2021-06-09 (Removed range [GH19])</dcterms:modified>
 </owl:ObjectProperty>`

What is the up to date element, DCTERMS:modified or RDFS:range?

**Comment by jodiw01** [comment]
Updated at https://id.loc.gov/ontologies/bibframe.html
