### ISSUE TITLE
change bf:noteType range from literal to resource?

### ISSUE THREAD

**Issue by NancyL** [lcnetdev/bibframe-ontology#109]
id.loc.gov has a vocabulary for NoteType with URIs. The ontology, however, states that bf:noteType has a domain of literal, meaning we cannot use the vocabulary with that property. Can this be changed?

**Comment by ntra00** [comment]
Nancy, the intent is to use the noteType field when there is not a defined notetype, hence the literal.
https://id.loc.gov/resources/instances/11568137.rdf has an example of a known  notetype:
```xml
<bf:note>
<bf:Note>
<rdf:type rdfs:resource="http://id.loc.gov/vocabulary/mnotetype/physical"/>
<rdfs:label>sd., col.</rdfs:label>
</bf:Note>
</bf:note>
```
