### ISSUE TITLE
Add bf:AccessionNumber class as a subclass if bf:Identifier

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#11]
Justification: Accession numbers are an important identifier for cultural heritage institutions to record and track an object in their collections. These numbers are also useful in the provenance of an object. BF2 does not explicit way to record accession numbers that are currently being recorded in MARC 541 $e. This issue was discussed during the Rare Material and ArtFrame Ontology Spring on March 2-3, 2017, and it was determined that accession numbers are an essential identifier and must have some way recording this information in a linked data ontology for cultural heritage and rare materials. See: https://github.com/LD4P/arm/blob/master/modeling_recommendations/accession_numbers.md.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by jak473** [comment]
Has LC considered this proposal? ARM is soon to finalize it's next release and will need to include AccessionNumber if LC does not incorporate into BF.

**Comment by ntra00** [comment]
We have it on a list of things we (LC) want to approve, so assuming planets align, it will become a subclass of Identifier.

**Comment by jak473** [comment]
Great, thanks @ntra00 ; do you have a sense of when this may happen?

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_AccessionNumber
