### ISSUE TITLE
The degree example seems to be erroneous

### ISSUE THREAD

**Issue by frosterus** [lcnetdev/bibframe-ontology#114]
The example found in https://id.loc.gov/ontologies/bibframe.html#p_degree seems to list a university as a degree (at least Google translate gives National Chengchi University as a translation of 國立政治大學) and degree as a label. The example found in https://id.loc.gov/ontologies/bibframe.html#p_grantingInstitution seems to be correct in this regard.

**Comment by ntra00** [comment]
Thanks for pointing this out. I would agree; the data should be in the institution field, 502$c but it's in 502$b,  I will see if we can fix the record and this example.

**Comment by ntra00** [comment]
I've updated the example and asked that the record be corrected as well.
[https://id.loc.gov/ontologies/bibframe.html#p_degree]
