### ISSUE TITLE
Add subclass bf:ClassificationNal to bf:Classification

### ISSUE THREAD

**Issue by NancyL** [lcnetdev/bibframe-ontology#119]
Hi, I'm writing this on behalf of the National Agricultural Library (NAL). They are currently developing templates for articles using BF via the Ex Libris BF project. They would like to be able to identify NAL classification in their descriptions since it is still being used in certain areas of the library. I am proposing the subclass bf:ClassificationNal to mesh with the other 4 subclasses provided: bf:ClassificationDdc, bf:ClassificationLcc, bf:Classification Udc & bf:ClassificationNlm.

While I realize that one may define on the fly any classification scheme from the Classification schemes list, there are two problems with this in this particular case:
1. NAL does not seem to be in that list, perhaps because officially they use LCC now. But there are new electronic documents that are in fact using the NAL number, often in tandem with the LCC
2. NAL has a particular MARC mapping--to the 070 field-- just as the other subclasses provided in the list do. Because of this, it seems to me to be easier all round if there were a particular subclass for the NAL class scheme that could then map directly to the MARC 070

The shape of the NAL classification number would be exactly what it is for Lcc:

bf:classification [a bf:ClassificationNal ;
    bf:classificationPortion "XXX" ;
    bf:itemPortion "XXX" ]
.

These would map to MARC as:
070 0# $a[bf:classficationPortion literal] $b [bf:itemPortion literal]

**Comment by jodiw01** [comment]
included in v2.4
