### ISSUE TITLE
Remove of the phrase “that is documented by a resource,” from the bf:Event definition

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#12]
Justification: This would allow bf:Events to be applied in contexts other than as the event content of a work, e.g. exhibitions, auctions, theft.

**Comment by sfolsom** [comment]
[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_Event
