### ISSUE TITLE
Add bf:OclcNumber as identifier subclass

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/bibframe-ontology#120]
To facilitate future data exchange activities with OCLC, add bf:OclcNumber as an subclass of bf:Identifier. This change could also streamline the output of OCLC numbers in RDF, from this:

<bf:identifiedBy>
<bf:Local>
<rdf:value>on1303623709</rdf:value>
<bf:assigner>
<bf:Agent rdf:about="http://id.loc.gov/vocabulary/organizations/ocolc"/>
</bf:assigner>
</bf:Local>
</bf:identifiedBy>

to this:

<bf:identifiedBy>
<bf:OclcNumber>
<rdf:value>on1303623709</rdf:value>
</bf:OclcNumber>
</bf:identifiedBy>

**Comment by klngwll** [comment]
A suggestion would be to add ID or Number to the Class (OclcID if broadly applicable, or OclcNumber if specific) and possibly specify relationship with https://id.loc.gov/vocabulary/identifiers/worldcat

**Comment by azaroth42** [comment]
Indication that the ontology is broken when you need to multiple your classes by the number of adopting institutions.

**Comment by jodiw01** [comment]
included in v2.4
