### ISSUE TITLE
Identifier types as a vocabulary instead of subclasses

### ISSUE THREAD

**Issue by frosterus** [lcnetdev/bibframe-ontology#123]
Would it make sense to change how the different identifier types are handled in BIBFRAME? This is related to issue #120 .

It seems cumbersome to include the various identifier types as dedicated Classes in the BIBFRAME datamodel. We at NLF have a need for a few new identifiers as well, but it seems it might make more sense to model identifiers similar to how, e.g., note types are handled using a separate vocabulary (https://id.loc.gov/vocabulary/mnotetype.html). This solution would not put stress on the data model when new identifier types are inevitably needed. The LC Standard Identifier list could work for this as is (https://id.loc.gov/vocabulary/identifiers.html).

**Comment by jarmosaarikko** [comment]
The BIBFRAME model has an editorial note for [bf:Identifier](https://id.loc.gov/ontologies/bibframe.html#c_Identifier)
_Editorial Note:	Any entry from the [Standard Identifiers vocabulary at ID](http://id.loc.gov/vocabulary/identifiers) may be used; all have been defined as a bf:Identifier_
See also #44    

Question 1:
I suspect any other controlled list of identifiers would be ok, too, if the identifiers are declared of this type without the need to add any more sublclasses to the Bibframe model?   

However, contrary to the Editorial note quoted above,  I noticed that on the LC list. there is only one type (skos:Concept)  defined for the identifiers. e.g. 
https://id.loc.gov/vocabulary/identifiers/wikidata.skos.nt  
`<http://id.loc.gov/vocabulary/identifiers/wikidata> 
     <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> 
     <http://www.w3.org/2004/02/skos/core#Concept>` .
 or
https://id.loc.gov/vocabulary/identifiers/isbn.skos.json
```
"@id": "http://id.loc.gov/vocabulary/identifiers/isbn",
"@type": [
"http://www.w3.org/2004/02/skos/core#Concept"
],
```
Question 2: 
Will you be fixing this and adding the types according to the Editorial note in the Bibframe model?

**Comment by jodiw01** [comment]
The list of Standard Identifiers (https://id.loc.gov/vocabulary/identifiers.html)  now includes bf:Identifier.
![image](https://github.com/user-attachments/assets/e73400a1-5541-4e1a-9726-8b880862cc9c)
