### ISSUE TITLE
Define inverse bf:arrangementOf for bf:arrangement

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#14]
Justification: inverses are critical to linked data environments, allowing automatic bi-directional linking from any dereferenced resource. Also, some linked data tools (e.g. Vitro) require assertions in both directions to navigate back and forth from resources.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
The inverse property has been created, but there were larger changes surrounding this property.  

See:  https://github.com/lcnetdev/bibframe-ontology/issues/77
