### ISSUE TITLE
Remove range bf:GenreForm from bf:genreForm

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#16]
Justification: It produces an undesirable entailment when linking directly to a skos:Concept vocabulary.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
Out of curiosity, can you provide an example of how this produces an undesirable entailment?  

I guess I'm wondering what about it makes it "undesirable?"

**Comment by sfolsom** [comment]
I think in most of these cases it's about trying to keep the distinction between skos:Concepts and RWOs. It requires making sure the class definitions are close enough every time we want to an external data source, rather than just letting the typing come from the external data source itself.

**Comment by NancyL** [comment]
I sent a question about this to Ray D. in October 2017. His answer (with the question) from Oct. 24 of that year is as follows:  3.  Is it really necessary to have ranges for such properties as bf:content,
bf:media, bf:carrier, bf:genreForm? If taken literally, this would seem to mean
that only a vocabulary that states it contains instances of bf:Content, etc. (okay
Steven brought it up). We are, at I think LC as well, generally taking for granted
that the LC vocabularies at least are instances of these classes and stating it,
but there is nowhere in the modeling of these vocabularies that states they are,
as they are with the LC names for example (this is why I've included you Nate).
It seems that to be using these vocabularies in a completely compatible way,
we would either need to state that these vocabularies are instances of the bf:
classes or remove the range restriction. The second seems to me to be
preferable, as it would allow different vocabularies--RDA for content, media,
carrier; other genre terms (AAT?) for genreForm. But perhaps there is some
reason for the restriction I don't know?

ANSWER from Ray: No.  This is an oversight, we thought we had removed ranges for these.  We'll do so.

**Comment by sfolsom** [comment]
To be clear, domain and range definitions don’t support “validation” except where classes are explicitly defined as incompatible. The primary issues here are that the BF is generally RWO oriented and library existing vocabs are concept/authority oriented and... when linking to RWOs outside of the library sphere, we don’t necessarily need the inferenced “new knowledge” type assertions on those entities.

**Comment by NancyL** [comment]
Agreed. My main point here is that Ray & Sally both agreed that the ranges should be removed (and thought they had been).

**Comment by melanieWacker** [comment]
PoCo also voted in favor (Dec. 2020) of removing the range of bf:GenreForm from bf:genreForm. This is an outcome of the final report of the PCC Task Group on Sinopia Application Profiles (https://www.loc.gov/aba/pcc/taskgroup/Sinopia-Profiles-TG-Final-Report.pdf)
From the report "The addition of ranges to BF properties introduces challenges regarding inferencing and linked data best practices. At a practical level, a range may restrict the breadth of possible vocabularies that are usable according to best practice. For example, catalogers might use AAT terms to describe a form or genre. These terms, however, are not bf:GenreForms."

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_genreForm
