### ISSUE TITLE
Expand definition of bf:GenreForm

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#17]
Expand definition of bf:GenreForm (The definition only refers to moving images in its examples. Some literary or art examples would be good, or just reusing the bf:genreForm definition which is simply "Form category or genre to which a resource belongs" which makes it much broader.)

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_GenreForm
