### ISSUE TITLE
Expand the definition of bf:subject

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#21]
We recommend removing "used with Work, Instance, or Item" from the bf:subject definition, so that it can apply to other types of entities, e.g. ExhibitionEvents.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_subject
