### ISSUE TITLE
Expand definition and intended use of bf:title

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#23]
Remove “Used with Work, Instance, or Item” on bf:title, to allow use with events and other resources, e.g. ExhibitionEvents.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_title
