### ISSUE TITLE
Remove domain and ranges from bf:appliedMaterial and bf:baseMaterial

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#24]
Justification: Removing the domain bf:Instance will allow the possibility to assert on bf:Items materials that that are not the same as an "ideal" bf:Instance. The ranges should remain unspecified to allow for use with materials vocabularies (e.g. Getty AAT) that do not declare their terms to be of type Material.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_appliedMaterial
https://id.loc.gov/ontologies/bibframe.html#p_baseMaterial
