### ISSUE TITLE
Add inverses of bf:appliedMaterial and bf:baseMaterial

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#25]
Justification: inverses are critical to linked data environments, allowing automatic bi-directional linking from any dereferenced resource. Also, some linked data tools (e.g. Vitro) require assertions in both directions to navigate back and forth from resources.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_baseMaterialOf
https://id.loc.gov/ontologies/bibframe.html#p_appliedMaterialOf
