### ISSUE TITLE
Create bf:material/bf:materialOf pair, and add rdfs:subPropertyOf assertions from bf:appliedMaterial and bf:baseMaterial

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#26]
Justification: A super property bf:material/bf:materialOf pair would be useful for situations where it's not applicable or clear how to decide whether a material is the base or applied.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_material
https://id.loc.gov/ontologies/bibframe.html#p_appliedMaterial
https://id.loc.gov/ontologies/bibframe.html#p_baseMaterial

https://id.loc.gov/ontologies/bibframe.html#p_materialOf
https://id.loc.gov/ontologies/bibframe.html#p_appliedMaterialOf
https://id.loc.gov/ontologies/bibframe.html#p_baseMaterialOf
