### ISSUE TITLE
Remove classes bf:AppliedMaterial and bf:BaseMaterial. 

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#28]
Justification: bf:appliedMaterial and bf:baseMaterial are sufficient.

We do not believe that BaseMaterial and AppliedMaterial are types of things. A material instance (e.g. brass) is simply a Material, and it may be used as the base material or the applied material in specific cases. A material which is a base material to one resource may be the applied material of another.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
This was rejected at this time.  We did create the more abstract bf:Material and made these existing classes subclasses of bf:Material.

https://id.loc.gov/ontologies/bibframe.html#c_Material
https://id.loc.gov/ontologies/bibframe.html#c_AppliedMaterial
https://id.loc.gov/ontologies/bibframe.html#c_BaseMaterial

Implementers should migrate to the more abstract class, but with the more specific properties.
