### ISSUE TITLE
Change definition of bf:Mount

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#29]
Change definition bf:Mount to be a mount object rather than a mount material, or remove the class and leave it to be defined by ArtFrame/RareMat groups along with other resource parts such as Binding, Frame, etc. This will allow a more consistent approach to both materials and parts.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
Hey @sfolsom instead of "changing" the definition, would adding "or Object" to the current definition resolve this?

**Comment by sfolsom** [comment]
I had to dust off my notes on this. :) I think the intent of this request was to treat things like Mounts as *parts* of a resource that can be made up of materials. It sounds like the "or Object" proposal would allow this, but also grandfather in Mounts as materials too. 

Personally, I'm meh about allowing both uses through the same class (querying would get weird across implementations), but I don't want to speak for ARM. Looping in folks who might be in a better position to to weigh in officially... cc: @jak473 and @gracianipicardo

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_Mount
