### ISSUE TITLE
Open up the domain of bf:extent

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#30]
Open up the domain of bf:extent so that extents that may vary from the “ideal Instance” can be captured on bf:Items. E.g. pages may be missing from a specific copy.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_extent
