### ISSUE TITLE
Remove rdfs:comment "Used with Work or Instance" from bf:colorContent

### ISSUE THREAD

**Issue by melanieWacker** [lcnetdev/bibframe-ontology#31]
Justification: While an rdfs:comment does not mean that bf:colorContent can only be used with Work or Instance, the ArtFrame working group nevertheless feels that it would avoid confusion to remove this recommendation altogether. There are a number of use cases, where we feel that colorContent should be more appropriately associated with the Item (e.g. a published print was hand colored after the fact)

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
Clarified comment.  https://id.loc.gov/ontologies/bibframe.html#p_colorContent
