### ISSUE TITLE
Add LimitationNote as a subclass of bf:Note

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#33]
Because limitation statements capture string values, rather than creating a distinct predicate, the proposal is to create a subclass of bf:Note, http://example.org/LimitationNote.

For more context on the recommendation, see: https://github.com/LD4P/arm/blob/master/modeling_recommendations/limitation_statements.md

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
Since ARM has established LimitationNote as a bf:Note type, the status of this request is unclear.

https://github.com/Art-and-Rare-Materials-BF-Ext/arm/blob/main/v1.0/ontology/arm_1_0.rdf

**Comment by jak473** [comment]
Right. We plan to use a notetype vocab rather than subclassing; I think you can close this request now.

https://github.com/Art-and-Rare-Materials-BF-Ext/arm/blob/main/v1.0/vocabularies/note_types.rdf
