### ISSUE TITLE
Consider using subclasses instead of bf:noteType

### ISSUE THREAD

**Issue by melanieWacker** [lcnetdev/bibframe-ontology#35]
Justification: Many notes can be attached to the appropriate node and then note type is therefore implied. That limits the cases where a noteType has to be defined. Using subclasses would provide a higher level of standardization. See also the related proposal https://github.com/lcnetdev/bibframe-ontology/issues/33

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
All members of this scheme - https://id.loc.gov/vocabulary/mnotetype - are of type bf:Note, meaning they can be used to indicate the note type in BIbframe.  We will likely add to this list over time; it is a pattern for others to consider.
