### ISSUE TITLE
Consider including arm attribution model into BF

### ISSUE THREAD

**Issue by melanieWacker** [lcnetdev/bibframe-ontology#36]
Justification: Attributions are generally applicable across all domains.
In the MARC 21 standard this has so far been handled by adding subfield j (attribution qualifier) to the 1xx field in the bibliographic record. The MARC Relator Terms contain “Attributed name” (http://id.loc.gov/vocabulary/relators/att) for use in this subfield. However, the ArtFrame group felt that attributions behaves somewhat differently from other relators such as artist or author.
Background: https://github.com/LD4P/arm/blob/master/modeling_recommendations/attributions.md
Note: The attribution modeling recommendation doc includes references to the arm activities model. The activities could be reformulated as contributions.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
The attribution model appears to have been removed from ARM.  Please re-open if I am mistaken.
