### ISSUE TITLE
Deprecate the bf:awards datatype property, and advocate for the use of the ARM Awards ontology

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#37]
Justification: The ARM Awards Ontology (https://ld4p.github.io/arm/award/ontology/0.1/award.html), though a relatively simple model, provides greater machine actionable expressivity over the current bf:awards. 

- In the ARM Awards Ontology awards are treated as RDF resources so that one can confidently query resources related to a particular award, e.g. given me all the resources related to <http://dbpedia.org/resource/Caldecott_Medal>. 
- The ARM Awards Ontology also provides an AwardReceipt class to allow one to assert **when** the award was received and **the nature of the receipt** (e.g. honorary mention, nominee). 

By deprecating bf:awards and using the ARM Award Ontology, the BIBFRAME community would have a single expressive pattern to link BIBFRAME resources to Awards.

Note: The ARM Award Ontology uses an Activity Pattern rather than the bf:Contribution, but the bf:Contribution pattern could easily replace the bf:Activity class.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
Did not deprecate the property, but did add a note advertising the ARM Ontology as an alternative.  This is a conservative decision. Time may suggest it be revisited.

https://id.loc.gov/ontologies/bibframe.html#p_awards
