### ISSUE TITLE
Deprecate the bf:custodialHistory datatype property, and advocate for the use of the ARM CustodialHistory ontology

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#38]
Justification: The ARM Custodial History Ontology (https://ld4p.github.io/arm/custodial_history/ontology/0.1/custodial_history.html), though a relatively simple model, provides greater machine actionable expressivity over the current  bf:custodialHistory. In the ARM Custodial History Ontology, custodial histories can have distinct related events that link to agents at a particular time an place. Together this allows to query when, where, and who has been involved with a particular item, and track the sequence of events.

By deprecating bf:custodialHistory and using the ARM Custodial History Ontology, the BIBFRAME community would have a single expressive pattern to link BIBFRAME resources to custodial histories.

Note: The ARM Custodial History Ontology uses an Activity Pattern rather than the bf:Contribution, but the bf:Contribution pattern could easily replace the arm:Activity class.

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
Did not deprecate the property, but did add a note advertising the ARM Ontology as an alternative.  This is a conservative decision. Time may suggest it be revisited.

https://id.loc.gov/ontologies/bibframe.html#p_custodialHistory
