### ISSUE TITLE
request inverse of bf:contribution

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#4]
Create as inverse of bf:contribution (bf:isContributionOf) to link from an Agent to the Work. This is particularly important in a linked data environment, if only the Agent URI is known/dereferenced, rather than coming from the point of view of the Work. See also: https://github.com/lcnetdev/bibframe-ontology/issues/3

**Comment by kirkhess** [comment]
We would like a use case for this issue and #3

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_contributionOf
