### ISSUE TITLE
Deprecate bf:FontSize and predicate bf:fontSize, and advocate for the use of related terms in the ARM Core Ontology

### ISSUE THREAD

**Issue by sfolsom** [lcnetdev/bibframe-ontology#40]
Justification: BF is right to separate font from the other types of “notation,” since font refers to the style in which symbols are printed rather than to the symbol systems themselves. However, typeface is semantically related more to font size than to these symbol systems. Further, BF would include in addition to font size, other properties of a font - typeface and style.

The ARM Core Ontology (https://ld4p.github.io/arm/core/ontology/0.1/core.html), includes the patterns to allow Fonts and Handwriting to be handled distinctly from Notations. For more information on the recommendation see: https://github.com/LD4P/arm/blob/master/modeling_recommendations/fonts_handwriting_notations.md

By deprecating bf:FontSize and predicate bf:fontSize and using the related terms from the ARM Core Ontology, the BIBFRAME community would have a single expressive pattern to describe Fonts, Handwriting, and Notations within BIBFRAME implementations.

The following two minor changes to notation related term definitions would complete the distinction between Notations and style elements capture in Fonts and Handwriting:
- Remove “typescript” from existing notation-related definitions.
- Change “alphabet” in notation-related definitions to “writing system,” 

[This recommendation was made on behalf of the LD4P Art & Rare Materials BIBFRAME Ontology Extension (https://github.com/LD4P/arm).]

**Comment by kefo** [comment]
Did not deprecate the property or class, but did add a note advertising the ARM Ontology as an alternative.  This is a conservative decision. Time may suggest it be revisited.

https://id.loc.gov/ontologies/bibframe.html#p_fontSize
