### ISSUE TITLE
Make derivedFrom an ObjectProperty

### ISSUE THREAD

**Issue by klngwll** [lcnetdev/bibframe-ontology#41]
derivedFrom in AdminMetadata is defined as a literal but says it should contain a "Link to the metadata that was the source of the data." For it to be usable as a proper link it needs to be an ObjectProperty.

http://id.loc.gov/ontologies/bibframe.html#p_derivedFrom

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_derivedFrom
