### ISSUE TITLE
Label and usage of PublisherNumber

### ISSUE THREAD

**Issue by klngwll** [lcnetdev/bibframe-ontology#42]
It seems that PublisherNumber (http://id.loc.gov/ontologies/bibframe.html#c_PublisherNumber) has inherited the rather vague label "Other publisher number" from 028 i1=5 in MARC21, which in that context makes more sense because of its more "list-like" nature. I suggest it would be more aligned with the BF2/RDF model to just use "Publisher number" allowing it to be a more general Class and let the definition clarify usage.

Possibly this is also a reflection of the more specialized publisher numbers for music and video and it could make sense that these were instead subClasses of PublisherNumber.

**Comment by thisismattmiller** [comment]
Fixed with #47 Bibframe 2.0.1
