### ISSUE TITLE
Consider adding more subclasses to Identifier

### ISSUE THREAD

**Issue by klngwll** [lcnetdev/bibframe-ontology#44]
[Identifier](http://id.loc.gov/ontologies/bibframe.html#c_Identifier) has several useful subClasses. A suggestion to add some widely used coordinating identifiers for Agents like Orcid and Viaf would be useful complementing the already included Isni subClass.

**Comment by kefo** [comment]
All members of the [Identifier Sources scheme](https://id.loc.gov/vocabulary/identifiers) are now of type bf:Identifier to make clear their usability in Bibframe.
