### ISSUE TITLE
Some bflc property URIs do not resolve

### ISSUE THREAD

**Issue by acka47** [lcnetdev/bibframe-ontology#48]
From https://github.com/hbz/swib18-workshop/issues/33#issue-380177307. There are at least four bflc properties used in the Bibframe works dataset where the URIs do not resolve:

`http://id.loc.gov/ontologies/bflc/consolidates`, `http://id.loc.gov/ontologies/bflc/relatorMatchKey`, `http://id.loc.gov/ontologies/bflc/procInfo`, `http://id.loc.gov/ontologies/bflc/profile`

**Comment by kirkhess** [comment]
This was fixed a while ago...
