### ISSUE TITLE
issuedWith has different domain and range than MARC mapping.

### ISSUE THREAD

**Issue by klngwll** [lcnetdev/bibframe-ontology#5]
The mapping of MARC field 777 says bf2:issuedWith should be on a Work entity, but the RDF says issuedWith is restricted to Instances. Either issuedWith needs a a broader domain and range to allow for more entities or the mapping needs to be revised.

---
777 -   ISSUED WITH ENTRY (R) | W - issuedWith
---
<owl:SymmetricProperty rdf:about="http://id.loc.gov/ontologies/bibframe/issuedWith">
    <rdfs:domain rdf:resource="http://id.loc.gov/ontologies/bibframe/Instance"/>
    <rdfs:range rdf:resource="http://id.loc.gov/ontologies/bibframe/Instance"/>
    <skos:definition>Resource that is issued on the same carrier as the resource being described.</skos:definition>
    <rdfs:subPropertyOf rdf:resource="http://id.loc.gov/ontologies/bibframe/accompanies"/>
    <rdfs:label>Issued with</rdfs:label>
    <dcterms:modified>2016-04-21 (New)</dcterms:modified>
  </owl:SymmetricProperty>

**Comment by kefo** [comment]
Fixed in 2019.
