### ISSUE TITLE
originDate and originPlace

### ISSUE THREAD

**Issue by klngwll** [lcnetdev/bibframe-ontology#50]
The labels for [originDate](http://id.loc.gov/ontologies/bibframe.html#p_originDate) (Associated title date) and [originPlace](http://id.loc.gov/ontologies/bibframe.html#p_originPlace) (Associated title place) suggest they are only used in association with a title. However the definition and domain states that they are both used with the work entity. Updating the labels to simply "Origin date" and "Origin place" would make these properties less ambiguous and not locked down in context.

Another way forward could be to instead use something like a single origin objectProperty and class to be able to make more expressive statements with for example date and place. Comparable to the possibilities with the [capture](http://id.loc.gov/ontologies/bibframe.html#p_capture) property.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_originDate
https://id.loc.gov/ontologies/bibframe.html#p_originPlace
