### ISSUE TITLE
Embed more metadata about the vocabulary itself

### ISSUE THREAD

**Issue by dbs** [lcnetdev/bibframe-ontology#52]
Following the Linked Open Vocabulary [best practices](https://lov.linkeddata.es/Recommendations_Vocabulary_Design.pdf), there are a few statements that would be useful additions to the `owl:Ontology` element:

- `dc:description` to describe the purpose of the vocabulary
- `dc:issued` to track the first issuance of the vocabulary
- `rdfs:comment` to include a changelog for the major revisions
- all of the rights & property statements (`dc:rights`, `cc:license`, `dc:publisher`, `dc:contributor`)

Also we should indicate that the language is `xml:lang="en"` throughout, to better support translation efforts.

**Comment by dbs** [comment]
Linked Open Vocabulary updated its [BIBFRAME listing](https://lov.linkeddata.es/dataset/lov/vocabs/bf) over the weekend to incorporate the new base URI for the vocabulary. Note, however, that it is still using the old (now inaccurate - there is no mention of Item for example) BIBFRAME 1.0 description because the current BIBFRAME 2.0 ontology does not include a dcterms:description element, etc.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.rdf
