### ISSUE TITLE
owl:ontologyIRI isn't defined by OWL?

### ISSUE THREAD

**Issue by dbs** [lcnetdev/bibframe-ontology#53]
http://www.w3.org/2002/07/owl#ontologyIRI does not exist, which leads to an accusation of namespace hijacking in tools like http://oops.linkeddata.es/

While the [functional-style specification for OWL 2](https://www.w3.org/TR/owl2-syntax/) does include an ontologyIRI property, the OWL2 serialization at http://www.w3.org/2002/07/owl explicitly states that it is only a partial description of OWL2.

Perhaps the ontologyIRI property is available from a different namespace, but as it cannot be resolved at the given URI, I would recommend removing it from the BIBFRAME vocab definition.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.rdf
