### ISSUE TITLE
Consider adding subclass for government document classification numbers to bf:Classification

### ISSUE THREAD

**Issue by RobertRohr** [lcnetdev/bibframe-ontology#55]
Consider adding a class for government document classification numbers as a subclass of bf:Classification.
Justification: Libraries that are depositories for federal, state, and international government documents use government document classification schemes such as Superintendent of Documents classification system (sudocs) and United Nations document series symbols (undocs).

**Comment by kefo** [comment]
All members of the [Classification Source sheme]{https://id.loc.gov/vocabulary/classSchemes) are now of bf:Classification type to advertise their usability in Bibframe.

**Comment by NancyL** [comment]
so to be clear on the implementation of this...
We would have:
bf:classification [a bf:Classification ;
  rdfs:type http://id.loc.gov/vocabulary/classSchemes/sudocs ;
  but then???
with the other schemes we would use bf:classificationPortion and bf:itemPortion, but these divisions don't really exist in these numbers. But it would be nice for all to align. So maybe bf:itemPortion only?

**Comment by RobertRohr** [comment]
Considering that in government document classification schemes the agency number is the class number, I would say we could use both bf:classificationPortion and bf:itemPortion.
