### ISSUE TITLE
Consider to widen definition and range of ensemble

### ISSUE THREAD

**Issue by klngwll** [lcnetdev/bibframe-ontology#56]
Consider to widen the definition of [bf:ensemble] and add Class Ensemble (http://id.loc.gov/ontologies/bibframe.html#p_ensemble).

Justification is that the definition and range of ensemble is now only intended for musical ensembles which is more narrow than the "general" definition of an ensemble and does not accommodate future needs to add other types like theatre- or dance groups.

Suggest to widen the definition of the ensemble property to include any types of ensembles, add an Ensemble BaseClass and make MusicEnsemble its subClass.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_Ensemble
https://id.loc.gov/ontologies/bibframe.html#c_MusicEnsemble
https://id.loc.gov/ontologies/bibframe.html#p_ensemble
