### ISSUE TITLE
Declare bflc namespace in bflc.rdf

### ISSUE THREAD

**Issue by greeve** [lcnetdev/bibframe-ontology#58]
Please declare the bflc namespace in the `rdf:RDF` tag of `bflc.rdf`:

```
xmlns:bflc="http://id.loc.gov/ontologies/bflc/"
```

**Comment by kefo** [comment]
Should be there now: https://id.loc.gov/ontologies/bflc.rdf and https://id.loc.gov/ontologies/bibframe.rdf

**Comment by greeve** [comment]
Awesome! Thanks!
