### ISSUE TITLE
Request inverse property for bf:adminMetadata

### ISSUE THREAD

**Issue by NancyL** [lcnetdev/bibframe-ontology#59]
Sinopia, in part, makes use of un-nested profiles in order that we can relate resource templates bi-directionally, so that we relate the work to an instance and an instance to a work. One template we are not able to do this using BF vocabulary is bf:adminMetadata. We are temporarily going to use bflc:target, but it would make more sense to have the inverse property bf:adminMetadataFor.

**Comment by ntra00** [comment]
We're going to add it as a bflc property.

**Comment by NancyL** [comment]
hmm, they are still not collapsible if the field is mandatory or already has metadata in it. I think there were requests for this as well.

**Comment by kefo** [comment]
I don't know if I follow the concern/issue/comment, @NancyL .   What aren't collapsible if which field is mandatory?

**Comment by NancyL** [comment]
oops sorry. It ended up on the wrong hub somehow. Sorry, nothing at all to do with this! And thank you for responding to me so quickly.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_adminMetadataFor
