### ISSUE TITLE
Cannot dereference bflc:indexedIn

### ISSUE THREAD

**Issue by klngwll** [lcnetdev/bibframe-ontology#6]
Bibliographic field 510 in MARC is mapped to bflc:indexedIn (http://id.loc.gov/ontologies/bflc/indexedIn) but it is not RDF dereferencable, which either indicates an incorrect mapping or a future prospect for something which not yet exists in the bf/bflc RDF?

**Comment by thisismattmiller** [comment]
Fixed with BFLC 2.1.0 http://id.loc.gov/ontologies/bflc/indexedIn now dereferencable
