### ISSUE TITLE
expand domain/range of bf:assigner

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/bibframe-ontology#60]
Currently, bf:assigner can only be used with Admin Metadata. However, assigner agents appear in many places in a MARC record that do not map to Admin Metadata. For example, "assigning agency" is a commonly-used phrase in the identifier block of the MARC format (fields 010-090)

Can the domain of bf:assigner be extended to works, instances, and items too?

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_assigner
