### ISSUE TITLE
Remove domain/range from bf:issuedWith

### ISSUE THREAD

**Issue by ntra00** [lcnetdev/bibframe-ontology#62]
http://id.loc.gov/ontologies/bibframe/issuedWith.rdf is a linking property between resources. It s a subproperty of bf:accompanies, which is a subproperty of bf:relatedTo.
The other subproperties of bf:accompanies are Work to Work relators; this is the only one that is "Instance to Instance".  In theory it's possible to link Instances, but in practice if all links are at the Work level, it's much easier to program consistently.  

Even if the issuedWith is describing something "bound with" or similiar, you can link to it's Work instead of directly to that Instance.

The 777 MARC tag conversion to BIBFRAME envisions this usage. 

https://www.loc.gov/bibframe/bftm/

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_issuedWith
