### ISSUE TITLE
Remove the range from any property that might be considered pointing to an agent

### ISSUE THREAD

**Issue by ntra00** [lcnetdev/bibframe-ontology#63]
This is similar to issue 19, https://github.com/lcnetdev/bibframe-ontology/issues/19 requesting to remove ranges on the place properties.
We have noted that not all agent type institutions (or other creators/contributors, sources etc.) are in the LC Organizations list, nor in the LCNAF, but could be represented by URIs in other domains.  In fact with OCLC organization codes, it would be good to be able to reference a URI at OCLC instead of somehow having to bring them all into an LC list.

Rather than assuming or requiring that any external list be a subclass of bf:Agent, it would be safer to remove the range on these properties to allow broader usage:

- bf:agent
- bf:grantingInstitution
- bf:heldBy
- bf:assigner
- bf:descriptionModifier
- bf:source
- bf:acquisitionSource

This change will not have any backward compatibility issues.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_agent
https://id.loc.gov/ontologies/bibframe.html#p_grantingInstitution
https://id.loc.gov/ontologies/bibframe.html#p_heldBy
https://id.loc.gov/ontologies/bibframe.html#p_assigner
https://id.loc.gov/ontologies/bibframe.html#p_descriptionModifier
https://id.loc.gov/ontologies/bibframe.html#p_source
https://id.loc.gov/ontologies/bibframe.html#p_acquisitionSource
