### ISSUE TITLE
Clarify "Used with" entry on ontology display pages

### ISSUE THREAD

**Issue by ntra00** [lcnetdev/bibframe-ontology#64]
For properties that have a Domain, the “Used With” entry on the  ontology html presentation (eg.,   http://id.loc.gov/ontologies/bibframe.html#p_genreForm) has a link to the domain class, if any. 
If there is no domain, “Used with” is a text  entry such as “Used with Work or Instance”. That entry is expressed as an <rdfs:comment> in the actual ontology and therefore is not enforced, as <rdfs:domain rdf:resource="http://id.loc.gov/ontologies/bibframe/Instance"/> would be. 

Please clarify that entry to show that it suggests but does not prescribe use.

**Comment by kefo** [comment]
Done.
