### ISSUE TITLE
Remove domain of Item from bf:electronicLocator

### ISSUE THREAD

**Issue by ntra00** [lcnetdev/bibframe-ontology#66]
bf:electronicLocator is constrained to the Item resource, but there are times in serials where the uri they want to use is not a copy-specific uri, and it should be allowed on Instance.

Removing the domain constraint will not have a backwardly incompatible effect.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_electronicLocator
