### ISSUE TITLE
Label on Notation subClasses indicates relation not thing

### ISSUE THREAD

**Issue by klngwll** [lcnetdev/bibframe-ontology#67]
The label for the subClasses of [Notation](https://id.loc.gov/ontologies/bibframe.html#c_Notation) appends the word "used", which indicate a relation rather than the actual Script/Notation. Suggest to remove the word from the label to make the entity-description more clear (if there is an explicit need, you could update the [notation](https://id.loc.gov/ontologies/bibframe.html#p_notation) property label to something like "Notation used" but in my opinion it is already evident in the definition.)

Notation Subclasses:
https://id.loc.gov/ontologies/bibframe.html#c_Script 
https://id.loc.gov/ontologies/bibframe.html#c_MusicNotation
https://id.loc.gov/ontologies/bibframe.html#c_TactileNotation
https://id.loc.gov/ontologies/bibframe.html#c_MovementNotation

**Comment by kefo** [comment]
Done.
