### ISSUE TITLE
Consider adding bf:dateValid as a subproperty of bf:date

### ISSUE THREAD

**Issue by melanieWacker** [lcnetdev/bibframe-ontology#68]
The MODS Editorial Committee is in the process of updating the MODS to BF mapping and transformation. The MODS element dateValid has currently no equivalent in BIBFRAME.  
The definition can be found here:
https://www.loc.gov/standards/mods/userguide/origininfo.html#datevalid
Regardless of its location under mods:originInfo it is not related to a provision activity, but is rather a date or timespan for which the content of the resource (e.g. a map or a timetable) is valid. 
Simply using bf:date would lose all context of what this date or time span indicates and render the information useless.
Thank you for considering.

**Comment by kefo** [comment]
Can you please provide examples of how this would be used?  MODS examples would be helpful too.

Would it be more commonly associated with a Work or an Instance?  Should it have a defined domain of one or the other?  If not, why not?  If so, why?

**Comment by melanieWacker** [comment]
The definition in the DataCite schema captures the intended usage quite well and is actually better than the definition that we are giving in MODS. DataCite defines valid as "The date or date range during which the dataset or resource is accurate." I can email you some MODS examples of how it is used.

**Comment by jodiw01** [comment]
Valid dates are also defined in MARC 046

![image](https://user-images.githubusercontent.com/8515603/172232809-4f9786c5-05d7-4e21-a444-e961f6428268.png)

**Comment by jodiw01** [comment]
changed to bf:validDate to match existing *date properties.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_validDate
