### ISSUE TITLE
Consider adding  bf:Modification” under bf:ProvisionActivity

### ISSUE THREAD

**Issue by melanieWacker** [lcnetdev/bibframe-ontology#69]
The MODS Editorial Committee is in the process of updating the MODS to BF mapping and transformation. The MODS element mods:dateModified has currently no equivalent in BIBFRAME.
The definition can be found here:
https://www.loc.gov/standards/mods/userguide/origininfo.html#datemodified

mods:dateModified is useful for Websites or data sets. The MODS Editorial Committee proposes the addition of bf:Modification as a subclass of bf:ProvisionActivity (instead of bf:dateModified) since the modification of the resource may also include an agent for instance. With the addition of bf:Modification the date may simply be expressed using bf:date

**Comment by kefo** [comment]
Proposed definition?

**Comment by melanieWacker** [comment]
How about: "Information relating to modification of a resource."
This would follow the wording of the definitions of the other subclasses under bf:ProvisionActivity

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_Modification
