### ISSUE TITLE
Remove range bf:Language from bf:language

### ISSUE THREAD

**Issue by melanieWacker** [lcnetdev/bibframe-ontology#70]
This is a recommendation from the final report of the PCC Task Group on Sinopia Application Profiles (https://www.loc.gov/aba/pcc/taskgroup/Sinopia-Profiles-TG-Final-Report.pdf) -- See page 15.
From the report "The addition of ranges to BF properties introduces challenges regarding inferencing and linked data best practices. At a practical level, a range may restrict the breadth of possible vocabularies that are usable according to best practice. "
bf:language was identified as one of the properties where catalogers may want to use a term from a vocabulary where the current range does not apply.
Based on the report, PoCo voted on Dec. 18, 2020 to support this recommendation.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_language
