### ISSUE TITLE
Hub

### ISSUE THREAD

**Issue by kefo** [lcnetdev/bibframe-ontology#75]

**Comment by kefo** [comment]
Experimentation with bf:Hub began (at LC) more than three years ago, first becoming instantiated publically in June 2019.  Hubs, which are defined as a subclass of Work, are abstract resources that function as a bridge between two Works.  In this way, they function as aggregation and collocation resources.  They make it possible, for example, to gather all of the Spanish translations of Mark Twain’s _Tom Sawyer_ or to capture in which other BF Works Francisco Tarrega’s _Capricho árabe_ is included.  In LC’s experimentation, Hubs perform three functions as aggregators: as subjects, as related works, and as Works in the RDA sense.  Hubs, being BF Works, can be used as Subjects to describe other Works. 

Expected/recommended changes:

* bf:Hub  - new class
	* Label: Hub
	* Definition: An abstract resource that functions as a bridge between two Works.
	* SubClassOf: Work

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_Hub

**Comment by charchou-cloud** [comment]
Regarding the definition of Hub--"An abstract resource that functions as a bridge between two Works," can we change it into two "or multiple" Works? It's common to have multiple expressions/works for a Hub.
