### ISSUE TITLE
Definition of bf:hasExpression/expressionOf too restrictive

### ISSUE THREAD

**Issue by NancyL** [lcnetdev/bibframe-ontology#8]
The definition for both these properties states "For use to relate/connect Works under FRBR/RDA rules" (one property uses "relate"; the other uses "connect"). PMO would like to be able to use this property for modeling works, but not restrict it to either FRBR or RDA. Perhaps the sentence could be changed to read: "For use to relate Works under LRM/RDA guidelines or similar implementations".

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_hasExpression
https://id.loc.gov/ontologies/bibframe.html#p_expressionOf
