### ISSUE TITLE
Consider adding Time-span entity to align with LRM/RDA

### ISSUE THREAD

**Issue by timathom** [lcnetdev/bibframe-ontology#81]
IFLA LRM and RDA now include the Time-span entity to support contextual statements about periods of time related to a resource (defined as "a temporal extent having a beginning, an end and a duration").

Currently, support for dates in BIBFRAME is limited. Although it may be possible to express time spans in EDTF using the BF date properties, there is a strong use case for being able to explicitly identify date ranges and provide additional information about, or representations of, periods of time. See the Linked Art documentation for an example application of the concept: https://linked.art/model/base/#time-span-details.

**Comment by danmichaelo** [comment]
Just curious, why did you decide to close this issue, @timathom ?
