### ISSUE TITLE
expand domain/range of bf:originPlace

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/bibframe-ontology#83]
Testing of the marc2bibframe and bf2marc conversions on LC data shows that the intentionally simpler design of the BF ontology can create conflicts when creating MARC records.

One example is bf:originPlace (https://id.loc.gov/ontologies/bibframe.html#p_originPlace). It is a property of the Work. During the marc2bibframe conversion, data from MARC fields 257 (Country of producing entity) and 370 (Associated place) are both assigned to bf:originPlace. Since the bf2marc conversion cannot split otherwise-identical triples into different MARC tags, a single MARC tag will be assigned during the bf2marc conversion.

Based on the MARC definitions, place data in MARC 370 is applicable to the work, while place data in MARC 257 is applicable to the instance. Therefore, expanding the domain of bf:originPlace to Work and Instance (or removing any limitation) will enable each data element to be converted from MARC to BIBFRAME and from BIBFRAME to MARC separately.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_originPlace
