### ISSUE TITLE
Label of  replacementOf and replacedBy set erroneously to 'Preceded' by and 'Succeeded by' respectively

### ISSUE THREAD

**Issue by EdgarSchouten** [lcnetdev/bibframe-ontology#85]
https://github.com/lcnetdev/bibframe-ontology/blob/4f41f1d80e1f31f811e50109e0174e1eabf59ebb/bibframe.rdf#L5396-L5406

should be changed to 'Replacement of' 

https://github.com/lcnetdev/bibframe-ontology/blob/4f41f1d80e1f31f811e50109e0174e1eabf59ebb/bibframe.rdf#L5418-L5428

should be changed to 'Replaced by'

**Comment by ntra00** [comment]
Good catch. we will fix this in the next update.
