### ISSUE TITLE
Clarify Series Relationships

### ISSUE THREAD

**Issue by niklasl** [lcnetdev/bibframe-ontology#88]
In using the series relationships in BibFrame at the National Library of Sweden, we've encountered some problems. There is a need for clarification regarding their intended meaning and use, and possibly some corrections and adjustments. Among these is a perceived mixup in the [marc2bibframe2](https://github.com/lcnetdev/marc2bibframe2) conversion where these relationships are used.

## Relating Series and Issues

We are trying to express the relationship from an issue in a (newspaper) series to the series itself. In BF there are *four* relations defined for series, where two of them, bf:hasSeries and bf:seriesOf appear, on the surface, to relate a part to a whole (seemingly useful here). However, in the conversion specs, it becomes apparent that the first of this pair, bf:hasSeries, is used for bib 760 (subseries-to-parent-series relationship), and inversely, for bib 762, bf:hasSubseries is used (from the *second* pair, its inverse being bf:subseriesOf, which is unused in the MARC21 conversions).

In MARC21, bib 830 is commonly used to "refer to" the series of an individual issue. However bib 830 is *also* mapped to bf:hasSeries in the MARC21 to BIBFRAME conversion. Thus, these two pairs seem to have been mixed up.

To further the confusion, it seems like the base properties of bf:hasSubseries and bf:subseriesOf (the second pair) are wrong (in that they've gotten bf:hasPart and bf:partOf backwards).

## Proposed Corrections

We propose to address these problems with the following steps:

1. Correct the base properties for the bf:hasSubseries and bf:subseriesOf, and clarify their corresponding skos:definition texts accordingly.
2. Use these two for the relationships in bib 760 and 762 in the MARC21 conversion specification.
3. Define a new property for bib 830 (suggested name: bf:partOfSeries).
4. *Replace* the remaining use of bf:hasSeries with bf:partOfSeries (for book/issue-in-series) respectively. (It might be kept as a superproperty of these two more specific ones, if that is deemed necessary.)
5.  *Rename* bf:seriesOf to bf:seriesPart (being the inverse of bf:partOfSeries).

Following is a detailed description of our proposal.

## 1+2: Specifics For Sub-Series

These properties relate a subseries to a main series, and vice versa:
```turtle
bf:subseriesOf ; rdfs:label "Subseries of"; rdfs:subPropertyOf bf:hasPart .
bf:hasSubseries ; rdfs:label "Subseries" ; rdfs:subPropertyOf bf:partOf .
```
Given this (which we perceive as intended use):
```turtle
<subseries> bf:subSeriesOf <mainseries> .
<mainseries> bf:hasSubseries <subseries> .
```
the base properties ought to be:
```turtle
bf:subseriesOf ; rdfs:subPropertyOf bf:partOf . # instead of bf:hasPart
bf:hasSubseries ; rdfs:subPropertyOf bf:hasPart . # instead of bf:partOf
```
from which this can be inferred:
```turtle
<subseries> bf:partOf <mainseries> .  # bib 760
<mainseries> bf:hasPart <subseries> . # bib 762
```
And the mapping could then be revised to:
```xml
    <xsl:when test="$vTag='760'">bf:subseriesOf</xsl:when>
```
Which is much more cohesive considering that this is already the case in the existing conversion:
```xml
    <xsl:when test="$vTag='762'">bf:hasSubseries</xsl:when>
```

## 3,4,5: Disambiguating bf:hasSeries

The bf:hasSeries + bf:seriesOf pair can now be used for a part in a series (commonly an issue). We suggest a name change to clarify this:

* Rename bf:hasSeries to bf:partOfSeries (still subProperty of bf:partOf).
* Rename bf:seriesOf to bf:seriesPart (still subPropertyOf bf:hasPart).

And then revise the conversion mappings (for bib 830) accordingly to use bf:partOfSeries. (Its inverse is not used in those mappings.)

## Reference: The Current BibFrame Definitions

For reference, these are the *current* relevant definitions in BF (with some comments by us):
```turtle
bf:hasSeries a owl:ObjectProperty ;
    rdfs:label "In series" ;
    rdfs:subPropertyOf bf:partOf ;
    owl:inverseOf bf:seriesOf ;
    skos:definition "Resource in which the part has been issued; the title of the larger resource appears on the part." .

# This has not been used in the conversion mappings
bf:seriesOf a owl:ObjectProperty ;
    rdfs:label "Series container of" ;
    rdfs:subPropertyOf bf:hasPart ;
    owl:inverseOf bf:hasSeries ;
    skos:definition "Resource that is a part of a larger resource." .

bf:hasSubseries a owl:ObjectProperty ;
    rdfs:label "Subseries" ;
    rdfs:subPropertyOf bf:partOf ; # Ought to be: bf:hasPart
    owl:inverseOf bf:subseriesOf ;
    skos:definition "series resource that is part of another series." . 

# This has not been used in the conversion mappings
bf:subseriesOf a owl:ObjectProperty ;
    rdfs:label "Subseries of" ;
    rdfs:subPropertyOf bf:hasPart ; # Ought to be: bf:partOf
    owl:inverseOf bf:hasSubseries ;
    skos:definition "Series resource of which the described resource is a part." . 
```

**Comment by kirkhess** [comment]
Since Ray never wrote a whitepaper on series/subseries that I can find (maybe Kevin can double-check), this does needs some work to document how to use those properties. Also, LC catalogers doesn't use certain marc fields - I'm guessing they don't use 760/762 and 830 this way which makes sense if this has never come up before.

Niklas, I was curious if you have an example resources in Libris showing this situation? Especially any 760/762/830 examples with either a LCCN in the 010 (and/or an oclc# in the 035). I was thinking of looking in the sparql endpoint but I wasn't sure what to search for exactly, thanks!

**Comment by kirkhess** [comment]
There's only 120 records with a 762 and a LCCN in Worldcat. Of those 28 were authenticated with a 042 - I didn't check all of them but this one has a 762 in the LC catalog.

[](https://lccn.loc.gov/80646399/marcxml)

<datafield ind1="0" ind2=" " tag="762">
<subfield code="a">Brazil. Departmento Nacional da Producāo Mineral.</subfield>
<subfield code="t">Bibliografia</subfield>
<subfield code="w">(OCoLC)6613616</subfield>
</datafield>

The BIBFRAME version in ID doesn't render the subsieries but it's in there.
[](https://id.loc.gov/resources/works/11241605.html)
<bf:hasSubseries>
      <bf:Work>
	<bflc:aap>Brazil. Departmento Nacional da Producāo Mineral. Bibliografia</bflc:aap>
	<bflc:aap-normalized>brazildepartmentonacionaldaproducāomineralbibliografia</bflc:aap-normalized>
	<bf:contribution>
	  <bflc:PrimaryContribution>
	    <bf:agent>
	      <bf:Agent>
		<rdfs:label>Brazil. Departmento Nacional da Producāo Mineral.</rdfs:label>
	      </bf:Agent>
	    </bf:agent>
	  </bflc:PrimaryContribution>
	</bf:contribution>
	<bf:title>
	  <bf:Title>
	    <bf:mainTitle>Bibliografia</bf:mainTitle>
	  </bf:Title>
	</bf:title>
	<bf:hasInstance>
	  <bf:Instance>
	    <bf:title>
	      <bf:Title>
		<bf:mainTitle>Bibliografia</bf:mainTitle>
	      </bf:Title>
	    </bf:title>
	    <bf:identifiedBy>
	      <bf:Identifier>
		<rdf:value>6613616</rdf:value>
		<bf:assigner>
		  <bf:Agent>
		    <bf:code>OCoLC</bf:code>
		  </bf:Agent>
		</bf:assigner>
	      </bf:Identifier>
	    </bf:identifiedBy>
	  </bf:Instance>
	</bf:hasInstance>
      </bf:Work>
    </bf:hasSubseries>

Hope this helps!

**Comment by niklasl** [comment]
We fully understand that is takes some effort sorting out, and that since LC haven't used these relations much they're fairly unvetted.

(For the following, note that our endpoint contain descriptions using the [KBV](https://id.kb.se/vocab/) terms, who are mainly equivalencies or specializations of base BIBFRAME properties and classes.)

For bib 760/762, here is a [Libris search for resources with subseries](https://libris.kb.se/sparql?default-graph-uri=&query=SELECT+*+%7B+%3Fs+kbv%3AhasSubseries+%3Fo+%7D+LIMIT+100&format=text%2Fhtml&should-sponge=&timeout=0&signal_void=on). This yields e.g. https://libris.kb.se/q711d0w21jnl7w7#it. From that, there is an *unlinked* reference (via an old form record id we've yet to link up) to https://libris.kb.se/k3wz0n4w0zlj523#it which similarly "refers" back using `kbv:hasSeries`.

For bib 830, we've actually made a qualified relationship design here (`kbv:seriesMembership`), to be able to capture the number within a series (`kbv:seriesEnumeration`) for [resources being part of multiple series](https://libris.kb.se/sparql?default-graph-uri=&query=SELECT+*+%7B+%3Fs+kbv%3AseriesMembership+%3Fo1%2C+%3Fo2+.+filter+%28%3Fo1+%21%3D+%3Fo2%29++%7D+LIMIT+100&format=text%2Fhtml&should-sponge=&timeout=0&signal_void=on). Logically, this can be defined as `kbv:partOfSeries owl:propertyChainAxiom ( kbv:seriesMembership kbv:inSeries )` (basing that on the proposed `bf:partOfSeries`). Specifically for [newspapers](https://libris.kb.se/sparql?default-graph-uri=&query=SELECT+*+%7B+%3Fs+kbv%3AisIssueOf+%3Fo+%7D+LIMIT+100&format=text%2Fhtml&should-sponge=&timeout=0&signal_void=on), where numbering is integral to the issue (since they are always part of one series), we're trying out a new specialization, `kbv:isIssueOf` (which could be based on `bf:partOfSeries`, but right now is a sub-property of `bf:partOf`).

**Comment by jodiw01** [comment]
BIBFRAME ontology v2.4 should address these issues, but please let us know if something was missed.
