### ISSUE TITLE
bflc:aap & bflc:aap-normalized missing

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/bibframe-ontology#89]
Neither one of these resolve in the bflc ontology, and they have replaced rdfs:label in id.loc.gov in many different resources. What is the status on updating the bflc ontology? Or are these going to the bf ontology?

It appears to me that bflc:aap is the same as rdfs:label but maybe you can clarify that simply by updating the ontology with a definition or letting us know here. The bflc:aap-normalized seems harder to define w/o the process behind it as well.

Also, if there's some rule behind generating these two I'm sure the community would want that algorithm documented so you know what is supposed to be in an aap vs. a label. Thanks!

**Comment by jodiw01** [comment]
See https://github.com/lcnetdev/bflc-ontology/issues/2
