### ISSUE TITLE
Used with note in bf:hasPart/bf:partOf lacks bf:Event

### ISSUE THREAD

**Issue by NancyL** [lcnetdev/bibframe-ontology#9]
bf:hasPart/bf:partOf says is 1. Used with: Work, Instance, Item; and 2. has Expected Value: Work, Instance, Item. This listing should include Event in both cases.

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#p_hasPart
https://id.loc.gov/ontologies/bibframe.html#p_partOf
