### ISSUE TITLE
AdminMetadata class has 3 subclasses that look like mistakes

### ISSUE THREAD

**Issue by ntra00** [lcnetdev/bibframe-ontology#90]
Kirk Hess pointed out that AdminMetadata is subClassed As:  DescriptionConventions, GenerationProcess, and DescriptionAuthentication

Those are classes, but not subclasses of AdminMetadata. We should remove 
```xml
<rdfs:subClassOf rdf:resource="http://id.loc.gov/ontologies/bibframe/AdminMetadata"/>
```

from each.
See:
https://id.loc.gov/ontologies/bibframe/DescriptionConventions.rdf

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_GenerationProcess
https://id.loc.gov/ontologies/bibframe.html#c_DescriptionConventions
https://id.loc.gov/ontologies/bibframe.html#c_DescriptionAuthentication
