### ISSUE TITLE
Add bf:binding and bf:Binding

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/bibframe-ontology#91]
In 2021, the MARC Advisory Committee approved the creation of a field for structured information about binding. This concept should be added to the BF ontology, especially since RDA has a controlled list of terms (http://www.rdaregistry.info/termList/RDATypeOfBinding/).

New property: binding
URI: http://id.loc.gov/ontologies/bibframe/binding
Label: Binding
Definition: A method used to bind a published or unpublished resource, or other binding information.
Comment: Suggested use - With Instance or Item

New class: Binding
URI: http://id.loc.gov/ontologies/bibframe/Binding
Label: Binding
Definition: Information about methods used to bind a published or unpublished resource, or other binding information.
Used with: binding

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_Binding
https://id.loc.gov/ontologies/bibframe.html#p_binding
