### ISSUE TITLE
Interest in seeing bflc:TransliteratedTitle in the bf ontology

### ISSUE THREAD

**Issue by jimfhahn** [lcnetdev/bibframe-ontology#94]
Among our linked data cataloging team at Penn, there was interest in proposing that https://id.loc.gov/ontologies/bflc.html#c_TransliteratedTitle be considered for inclusion into the bf ontology. Is this something that could move from the bflc into the bf namespace? The catalogers want to make sure discovery systems can find transliterated titles and that resources remain discoverable by transliterated titles.

**Comment by jodiw01** [comment]
Updated at https://id.loc.gov/ontologies/bibframe.html
