### ISSUE TITLE
BFLC namelessProperty12

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/bibframe-ontology#95]
bflc must have some issue with the generation from its spreadsheet because there's a currently a property namelessProperty12 in the published ontology. 

https://id.loc.gov/ontologies/bflc.html#p_namelessProperty12

When you do the next update you can just make sure that goes away? Thanks!

**Comment by jodiw01** [comment]
Moved to https://github.com/lcnetdev/bflc-ontology/issues/5
