### ISSUE TITLE
new property for nonsort character count

### ISSUE THREAD

**Issue by ntra00** [lcnetdev/bibframe-ontology#96]
Consider adding a literal for the count of characters to ignore when sorting on another field, for example on a Title resource:

- mainTitle "The quick brown fox"
- nonSortNum "4"

This would mirror functionality of @ind2 in MARC, and help going back to MARC.
The bflc:titleSortKey does exist: https://id.loc.gov/ontologies/bflc/titleSortKey
but it has not been widely used and repeats almost the entire field.

**Comment by jodiw01** [comment]
Definition: "Number of characters at the start of a bf:mainTitle that should be skipped for indexing and sorting."

**Comment by NancyL** [comment]
Yes!

**Comment by kirkhess** [comment]
One thought I had was with a title resource like this:
        <bf:title>
            <bf:Title>
                <bf:mainTitle>Hainan hai yang yu ju yu fa</bf:mainTitle>
                <bf:mainTitle xml:lang="zh-hani">海南海洋渔具渔法</bf:mainTitle>
                <_:nonSortNum>4</_:nonSortNum>
            </bf:Title>
        </bf:title>

If you had 'nonSortNum' in a resource with more than one mainTitle which mainTitle is it for? 
Maybe 9 datatypes you could apply to mainTitles would be more specific?

**Comment by kirkhess** [comment]
you also could define a list like notetype for ind1 ad ind2 - then you could apply this in a lot of similar situations and it wouldn't be title-specific.

<bf:mainTitle rdf:datatype="http://id.loc.gov/vocabulary/indicator_2/4">The quick brown fox</bf:mainTitle>

**Comment by kefo** [comment]
Not a fan of the datatype idea.  That's not to say I have a good/better solution (but this sentence isn't an endorsement either).

**Comment by NancyL** [comment]
Okay, so when we developed this, we weren't modeling script/transliteration this way, and I guess we need to move there. For LC, I would suppose you could specify that it goes with the :mainTitle that doesn't have a language tag???

**Comment by NancyL** [comment]
In Sinopia, we will still have them in 2 separate title nodes, since we cannot at this time repeat properties in this way.

**Comment by kirkhess** [comment]
I think this new transiteration model is better because the literals are joined and the pattern works for any transliterations like provision activities and editions w/o a special class. 

Maybe there's no good solutions for legacy concepts like a the 245 ind2 so maybe a marc key is better?

**Comment by NancyL** [comment]
I don't disagree with the model, just we can't do it just now in Sinopia.  And I see with it there could even be 2 separate non-filing indicators.

the titleSortKey seems like it would have the same problem...

**Comment by NancyL** [comment]
So instead of having 2bf:maint
Tiles in a node, can’t we make 2 nodes?  That way you can have other parts of the title bound together rather than mixes

Sent from my iPhone

On Oct 4, 2022, at 6:09 PM, Jodi Williamschen ***@***.***> wrote:

﻿

Closed #96<https://github.com/lcnetdev/bibframe-ontology/issues/96> as completed.

**Comment by ntra00** [comment]
yes, it's fine to have two Titles with only one mainTitle each.
